# Site settings

title: "Suman Bharadwaj"
description: ""

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "true"
resume_name:                    "Suman Bharadwaj"
resume_title:                   "Customer Success @ R-Zero | Driving Product Adoption, Retention, Growth & Strategic Relationships in SaaS"

resume_header_contact_info:     "San Francisco Bay Area, CA • sumanbharadwaj1602@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p> Customer Success Manager with 6+ years of SaaS experience managing enterprise and mid-market accounts.<p></p></p> Proven track record in optimizing account health, driving adoption, and reducing churn.<p></p></p> Skilled in leading cross-functional teams to enhance engagement and deliver scalable solutions.</p>"

resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
resume_section_links:           false
resume_section_top:             false

resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/suman-bharadwaj"
resume_print_social_links:      true

resume_theme:                   default
