# This will toggle white ---> black (night mode)

name: toggle-night-mode

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Toggle night mode
        shell: bash
        run: |
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          sed -i 's/white;/black;/g' $GITHUB_WORKSPACE/_sass/_base.scss
          sed -i 's/black;/white;/g' $GITHUB_WORKSPACE/_sass/_variables.scss
          git commit -m "Toggle night mode" -a
          git push
